# Generated by Django 3.2.9 on 2021-11-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_tag', models.CharField(default='Awkward Blog from Awkward Men', max_length=50, verbose_name='Title Tag')),
                ('body', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to='post_pic', verbose_name='Image')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=50, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Login User')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theblog.category', verbose_name='Category')),
            ],
        ),
    ]
