# Generated by Django 3.2.9 on 2021-11-05 21:10

from django.db import migrations, models
import theblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.png', upload_to=theblog.models.user_directory_path),
        ),
    ]
