# Generated by Django 3.2.9 on 2021-11-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_auto_20211110_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
