# Generated by Django 3.2.8 on 2021-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Awkward Blog from Awkward Men', max_length=50),
        ),
    ]
