# Generated by Django 3.2.8 on 2021-10-31 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('c1', 'Cat c1'), ('c2', 'Cat c2')], default=datetime.datetime(2021, 10, 31, 11, 47, 51, 317414, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('s2', 'Sta s2'), ('s1', 'Sta s1')], default=datetime.datetime(2021, 10, 31, 11, 48, 15, 341200, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_pic'),
        ),
    ]
