# Generated by Django 3.2.9 on 2021-11-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_delete_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
    ]
