# Generated by Django 3.2.8 on 2021-10-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20211101_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('s1', 'Sta s1'), ('s2', 'Sta s2')], max_length=50, verbose_name='Status'),
        ),
    ]
