# Generated by Django 3.2.8 on 2021-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('c1', 'Cat c1'), ('c2', 'Cat c2')], max_length=50, verbose_name='Category'),
        ),
    ]
