# Generated by Django 3.2.8 on 2021-11-01 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 11, 1, 16, 10, 1, 159340, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
